[package]
name = "fin_converter_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9"
csv = "1"
bincode    = { version = "2.0.0-rc3", features = ["serde"] }
